BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `android_metadata` (
	`locale`	TEXT
);
INSERT INTO `android_metadata` (locale) VALUES ('en_US');
CREATE TABLE IF NOT EXISTS `PROVINCE_TALK` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`PROVINCETALK_NAME`	TEXT NOT NULL UNIQUE,
	`PROVINCETALK_PROVINCE_ID`	INTEGER,
	`FLAG`	INTEGER DEFAULT 0,
	FOREIGN KEY(`PROVINCETALK_PROVINCE_ID`) REFERENCES `PROVINCE`(`ID`)
);
INSERT INTO `PROVINCE_TALK` (ID,PROVINCETALK_NAME,PROVINCETALK_PROVINCE_ID,FLAG) VALUES (1,'นคร',1,0),
 (2,'เชียง',2,0);
CREATE TABLE IF NOT EXISTS `PROVINCE` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`PROVINCE_NAME`	TEXT NOT NULL
);
INSERT INTO `PROVINCE` (ID,PROVINCE_NAME) VALUES (1,'นครราชสีมา'),
 (2,'เชียงใหม่'),
 (3,'กาญจนบุรี'),
 (4,'ตาก'),
 (5,'อุบลราชธานี'),
 (6,'สุราษฎร์ธานี'),
 (7,'ชัยภูมิ'),
 (8,'แม่ฮ่องสอน'),
 (9,'เพชรบูรณ์'),
 (10,'ลำปาง'),
 (11,'อุดรธานี'),
 (12,'เชียงราย'),
 (13,'น่าน'),
 (14,'เลย'),
 (15,'ขอนแก่น'),
 (16,'พิษณุโลก'),
 (17,'บุรีรัมย์'),
 (18,'นครศรีธรรมราช'),
 (19,'สกลนคร'),
 (20,'นครสวรรค์'),
 (21,'ศรีสะเกษ'),
 (22,'กำแพงเพชร'),
 (23,'ร้อยเอ็ด'),
 (24,'สุรินทร์'),
 (25,'อุตรดิตถ์'),
 (26,'สงขลา'),
 (27,'สระแก้ว'),
 (28,'กาฬสินธุ์'),
 (29,'อุทัยธานี'),
 (30,'สุโขทัย'),
 (31,'แพร่'),
 (32,'ประจวบคีรีขันธ์'),
 (33,'จันทบุรี'),
 (34,'พะเยา'),
 (35,'เพชรบุรี'),
 (36,'ลพบุรี'),
 (37,'ชุมพร'),
 (38,'นครพนม'),
 (39,'สุพรรณบุรี'),
 (40,'ฉะเชิงเทรา'),
 (41,'มหาสารคาม'),
 (42,'ราชบุรี'),
 (43,'ตรัง'),
 (44,'ปราจีนบุรี'),
 (45,'กระบี่'),
 (46,'พิจิตร'),
 (47,'ยะลา'),
 (48,'ลำพูน'),
 (49,'นราธิวาส'),
 (50,'ชลบุรี'),
 (51,'มุกดาหาร'),
 (52,'บึงกาฬ'),
 (53,'พังงา'),
 (54,'ยโสธร'),
 (55,'หนองบัวลำภู'),
 (56,'สระบุรี'),
 (57,'ระยอง'),
 (58,'พัทลุง'),
 (59,'ระนอง'),
 (60,'อำนาจเจริญ'),
 (61,'หนองคาย'),
 (62,'ตราด'),
 (63,'พระนครศรีอยุธยา'),
 (64,'สตูล'),
 (65,'ชัยนาท'),
 (66,'นครปฐม'),
 (67,'นครนายก'),
 (68,'ปัตตานี'),
 (69,'กรุงเทพมหานคร'),
 (70,'ปทุมธานี'),
 (71,'สมุทรปราการ'),
 (72,'อ่างทอง'),
 (73,'สมุทรสาคร'),
 (74,'สิงห์บุรี'),
 (75,'นนทบุรี'),
 (76,'ภูเก็ต'),
 (77,'สมุทรสงคราม');
CREATE TABLE IF NOT EXISTS `CHECK_WATCH_LIST` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`LICENSE`	TEXT NOT NULL,
	`PROVINCE`	TEXT NOT NULL,
	`BRAND`	TEXT,
	`MODEL`	TEXT,
	`COLOR`	TEXT,
	`TYPE`	TEXT
);
CREATE TABLE IF NOT EXISTS `CHECK_FOUND_LIST` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`LICENSE`	TEXT NOT NULL,
	`PROVINCE`	TEXT NOT NULL,
	`TYPE`	TEXT,
	`DATE`	TEXT,
	`TIME`	TEXT,
	`LATITUDE`	INTEGER,
	`LONGTITUDE`	INTEGER
);
CREATE TABLE IF NOT EXISTS `ALPHABET_TALK` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`CHARTALK`	TEXT NOT NULL UNIQUE,
	`ALPHABETID`	INTEGER,
	`FLAG`	INTEGER DEFAULT 0,
	FOREIGN KEY(`ALPHABETID`) REFERENCES `ALPHABET`(`ID`)
);
INSERT INTO `ALPHABET_TALK` (ID,CHARTALK,ALPHABETID,FLAG) VALUES (1,'ขอไข่',2,0),
 (8,'พพพพพ',1,1),
 (10,'ััััััรรรรร',1,1),
 (11,'พน',1,1),
 (12,'นนนนน',1,1),
 (13,'ดก',2,2);
CREATE TABLE IF NOT EXISTS `ALPHABET` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`ALPHABET_NAME`	TEXT NOT NULL
);
INSERT INTO `ALPHABET` (ID,ALPHABET_NAME) VALUES (1,'ก'),
 (2,'ข'),
 (3,'ฃ'),
 (4,'ค'),
 (5,'ฅ'),
 (6,'ฆ'),
 (7,'ง'),
 (8,'จ'),
 (9,'ฉ'),
 (10,'ช'),
 (11,'ซ'),
 (12,'ฌ'),
 (13,'ญ'),
 (14,'ฎ'),
 (15,'ฏ'),
 (16,'ฐ'),
 (17,'ฑ'),
 (18,'ฒ'),
 (19,'ณ'),
 (20,'ด'),
 (21,'ต'),
 (22,'ถ'),
 (23,'ท'),
 (24,'ธ'),
 (25,'น'),
 (26,'บ'),
 (27,'ป'),
 (28,'ผ'),
 (29,'ฝ'),
 (30,'พ'),
 (31,'ฟ'),
 (32,'ภ'),
 (33,'ม'),
 (34,'ย'),
 (35,'ร'),
 (36,'ล'),
 (37,'ว'),
 (38,'ศ'),
 (39,'ษ'),
 (40,'ส'),
 (41,'ห'),
 (42,'ฬ'),
 (43,'อ'),
 (44,'ฮ');
COMMIT;
