BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `android_metadata` (
	`locale`	TEXT
);
CREATE TABLE IF NOT EXISTS `PROVINCE_TALK` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`PROVINCETALK_NAME`	TEXT NOT NULL UNIQUE,
	`PROVINCETALK_PROVINCE_ID`	INTEGER,
	`FLAG`	INTEGER DEFAULT 0,
	FOREIGN KEY(`PROVINCETALK_PROVINCE_ID`) REFERENCES `PROVINCE`(`ID`)
);
CREATE TABLE IF NOT EXISTS `PROVINCE` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`PROVINCE_NAME`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `CHECK_WATCH_LIST` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`LICENSE`	TEXT NOT NULL,
	`PROVINCE`	TEXT NOT NULL,
	`BRAND`	TEXT,
	`MODEL`	TEXT,
	`COLOR`	TEXT,
	`TYPE`	TEXT
);
CREATE TABLE IF NOT EXISTS `CHECK_FOUND_LIST` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`LICENSE`	TEXT NOT NULL,
	`PROVINCE`	TEXT NOT NULL,
	`TYPE`	TEXT,
	`DATE`	TEXT,
	`TIME`	TEXT,
	`LATITUDE`	INTEGER,
	`LONGTITUDE`	INTEGER
);
CREATE TABLE IF NOT EXISTS `ALPHABET_TALK` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`CHARTALK`	TEXT NOT NULL UNIQUE,
	`ALPHABETID`	INTEGER,
	`FLAG`	INTEGER DEFAULT 0,
	FOREIGN KEY(`ALPHABETID`) REFERENCES `ALPHABET`(`ID`)
);
CREATE TABLE IF NOT EXISTS `ALPHABET` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`ALPHABET_NAME`	TEXT NOT NULL
);
COMMIT;
